apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rottenbikes

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment-api.yaml
  - service-api.yaml
  - deployment-ui.yaml
  - service-ui.yaml
