apiVersion: v1
kind: Secret
metadata:
  name: rottenbikes-secrets
type: Opaque
stringData:
  DB_USER: "rottenbikes"
  DB_PASSWORD: "rottenbikes"
  HCAPTCHA_SECRET: "0x0000000000000000000000000000000000000000"
